on:
  workflow_dispatch:
  push:
    branches:
      - master

name: Test, Build and Release apk

env:
  PROPERTIES_PATH: './android/key.properties'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Replace Icon
        run: |
          if [ -f icon_new.png ]; then
            cp icon_new.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          fi

      - name: Extract version
        id: extract_version
        run: |
          echo "version=v1.0.0" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17.x'

      - name: Cache Gradle dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup the Flutter environment.
        run: |
          pip install -U yq
          echo "FLUTTER_VERSION=$(yq -r .environment.flutter pubspec.yaml | sed 's/\^//g')" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      - name: Get Flutter dependencies.
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug --target-platform=android-arm64

      - name: Release debug APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: gokadze/Musify
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-debug.apk
          asset_name: Utopia-Music-arm64.apk
          tag: ${{ steps.extract_version.outputs.version }}
          prerelease: false
          overwrite: true
